apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: Ctsang
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ctsang-harbor-project/lab-env-repo:1.0
        ports: 5432
        - containerPort: <CONTAINER PORT>
